### ISSUE TITLE
Exercise structure

### ISSUE THREAD

**Issue by ludwig-austermann** [SmartRustLearning/Rattle#1]
My idea is to have kind of the following exercise structure.
```
exercise1/
  lib1.rs   <-- here predef. stuff is defined, visible but non editable
  test1.rs  <-- tests to check completion of exercise, visible?
  task1.rs  <-- the default file, where the user starts of from
  info1.md  <-- information / task / story
  config.toml / json <-- config w/ hints, name, ... from rustlings?
```

This way it is easy to implement depending exercises, by adding all enumerated files. The user will then in the third round have
```
lib = lib1 + lib2 + lib3
test = test3
task = task3
info = (info1 + info2) + info3
```

**Comment by sacha-l** [comment]
I like the model in general because it'll allows us to have players build on top of their solutions as they progress.

Not sure we need this functionality for every "game" though. Some of these fields should be optional without breaking expected schema. Just putting this here to note.
